version: "3.7"

services:
  feedback-backend:
    image: feedback-backend
    deploy:
      replicas: 5
    ports:
      - 8090:4040
    networks:
      - private-network
    environment: 
      - DB_ADDRESS=database-mongo
      - DB_PORT=27017
      - PORT=4040
    depends_on:
     - database-mongo

  database-mongo:
    image: mongo:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - private-network
    volumes:
      - type: volume
        source: mydata
        target: /data/db
        volume:
          nocopy: true

volumes:
  mydata:

networks:
  private-network:
    name: private-network
    driver: overlay