version: "3.7"

services:
  feedback-backend:
    image: feedback-backend
    deploy:
      replicas: 5
    ports:
      - 8090:4040
    networks:
      - private-network
    environment: 
      - DB_ADDRESS=database-mongo
      - DB_PORT=27017
      - PORT=4040
    depends_on:
     - database-mongo

  database-mongo:
    image: mongo:latest
    networks:
      - private-network
    volumes: 
      - mydata:/data/db

volumes:
  mydata:

networks:
  private-network:
    name: private-network
    driver: overlay